### ISSUE TITLE
Try to solve this issue (KeyError: 'sapi5')

### ISSUE THREAD

**Issue by ayushete02** [subhadip-saha-05/Python-Voice-Assistant#2]
`Traceback (most recent call last):
File "/home/jay/.local/lib/python3.9/site-packages/pyttsx3/init.py", line 20, in init
eng = _activeEngines[driverName]
File "/usr/lib/python3.9/weakref.py", line 134, in getitem
o = self.data[key](https://github.com/nateshmbhat/pyttsx3/issues/190)
KeyError: 'sapi5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/jay/Desktop/Simple AI.py", line 6, in
engine = pyttsx3.init('sapi5')
File "/home/jay/.local/lib/python3.9/site-packages/pyttsx3/init.py", line 22, in init
eng = Engine(driverName, debug)
File "/home/jay/.local/lib/python3.9/site-packages/pyttsx3/engine.py", line 30, in init
self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
File "/home/jay/.local/lib/python3.9/site-packages/pyttsx3/driver.py", line 50, in init
self._module = importlib.import_module(name)
File "/usr/lib/python3.9/importlib/init.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1030, in _gcd_import
File "", line 1007, in _find_and_load
File "", line 986, in _find_and_load_unlocked
File "", line 680, in _load_unlocked
File "", line 790, in exec_module
File "", line 228, in _call_with_frames_removed
File "/home/jay/.local/lib/python3.9/site-packages/pyttsx3/drivers/sapi5.py", line 1, in
import comtypes.client # Importing comtypes.client will make the gen subpackage
ModuleNotFoundError: No module named 'comtypes'`

**Comment by subhadip-saha-05** [comment]
make sure you've installed all packages with pip

**Comment by ayushete02** [comment]
I had installed
Also i google this error but still I am facing the same situation.

**Comment by subhadip-saha-05** [comment]
Dm me personally in Discord or mail me
