### ISSUE TITLE
Keyerror='sapi5' error for code to find driver

### ISSUE THREAD

**Issue by nisarg213122** [subhadip-saha-05/Python-Voice-Assistant#41]
I wrote this code in Dec last year; at that time, it was working perfectly, but now it isn't. Even though I installed sapi5 from the Microsoft download centre, it still shows the same error. I installed previous versions of pyttsx3, but still same problem persists. Now it doesn't even show the drivers or anything. I'm running this code in VS code btw.

Code: 

import pyttsx3 as p
engine=p.init()
voices=engine.getProperty('voices')
engine.setProperty('voice', voices[0].id)
engine.say("Hey")
engine.runAndWait()

Error: 
PS C:\Users\admin> & C:/Python311/python.exe "c:/Users/admin/Desktop/Advait/test run.py"
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\pyttsx3\__init__.py", line 20, in init
    eng = _activeEngines[driverName]
          ~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Python311\Lib\weakref.py", line 136, in __getitem__
    o = self.data[key]()
        ~~~~~~~~~^^^^^
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\admin\Desktop\Advait\test run.py", line 2, in <module>
    engine=p.init()
           ^^^^^^^^
  File "C:\Python311\Lib\site-packages\pyttsx3\__init__.py", line 22, in init
    eng = Engine(driverName, debug)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pyttsx3\engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pyttsx3\driver.py", line 52, in __init__
    self._driver = self._module.buildDriver(weakref.proxy(self))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pyttsx3\drivers\sapi5.py", line 23, in buildDriver
    return SAPI5Driver(proxy)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pyttsx3\drivers\sapi5.py", line 43, in __init__
    self.setProperty('voice', self.getProperty('voice'))
  File "C:\Python311\Lib\site-packages\pyttsx3\drivers\sapi5.py", line 88, in setProperty
    token = self._tokenFromId(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pyttsx3\drivers\sapi5.py", line 72, in _tokenFromId
    raise ValueError('unknown voice id %s', id_)
ValueError: ('unknown voice id %s', 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Speech_OneCore\\Voices\\Tokens\\MSTTS_V110_enUS_DavidM')

**Comment by subhadip-saha-05** [comment]
What OS Do you use ?

**Comment by nisarg213122** [comment]
> 

Windows 11. I again tried the same code in my dad's lapppy(he's is also windows 11 but with better specs than mine) and the code ran smoothly. No errors. Both had the same libraries installed.
